// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using arkano.data.daccess.Context;

namespace arkano.data.daccess.Migrations
{
    [DbContext(typeof(ArkanoEfContext))]
    partial class ArkanoEfContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("arkano.common.domain.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Begin");

                    b.Property<DateTime>("End");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("arkano.common.domain.DummyTestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("DummyTestModels");
                });

            modelBuilder.Entity("arkano.common.domain.OtroDummyTestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("OtroDummyTestModels");
                });

            modelBuilder.Entity("arkano.common.domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BestFriendId");

                    b.Property<DateTime>("BornDate");

                    b.Property<string>("CI");

                    b.Property<int?>("CourseId");

                    b.Property<string>("Name");

                    b.Property<string>("Surename");

                    b.HasKey("Id");

                    b.HasIndex("BestFriendId");

                    b.HasIndex("CourseId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("arkano.common.domain.Student", b =>
                {
                    b.HasOne("arkano.common.domain.Student", "BestFriend")
                        .WithMany()
                        .HasForeignKey("BestFriendId");

                    b.HasOne("arkano.common.domain.Course")
                        .WithMany("StudentsIn")
                        .HasForeignKey("CourseId");
                });
#pragma warning restore 612, 618
        }
    }
}
